---
- name: Create directory for zeroMQ build
  file: path=/zeromq/ state=directory mode=0744

- name: Get zeroMQ tarball
  get_url: url=http://download.zeromq.org/zeromq-2.2.0.tar.gz dest=/zeromq/ mode=0744

- name: Untar and uncompress (g-zip compression) the zeroMQ tarball
  command: tar -xvf zeromq-2.2.0.tar.gz chdir=/zeromq/

# Do I have to change the directory for every command performed in this directory?  How may I get the current working directory?
- name: Run zeroMQ configuration
  command: ./configure chdir=/zeromq/zeromq-2.2.0/

- name: Make zeroMQ
  command: make chdir=/zeromq/zeromq-2.2.0/

- name: Run a system-wide install of zeroMQ
  command: make install chdir=/zeromq/zeromq-2.2.0/

- name: Create nessecary links
  command: ldconfig chdir=/zeromq/zeromq-3.2.2/
