---
- name: install rvm
  shell: \curl -L https://get.rvm.io | bash -s stable --autolibs=3 creates=/home/users/{{ user }}/.rvm

- name: install ruby
  shell: /home/users/{{ user }}/.rvm/bin/rvm install --default {{ ruby }} creates=/home/users/{{ user }}/.rvm/rubies/{{ ruby }}

